name: Daily Startup Digest to Notion

on:
  schedule:
    - cron: "30 2 * * *" # 02:30 UTC = 08:00 IST
  workflow_dispatch: {}

jobs:
  run-digest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser openai requests

      - name: Show Python version
        run: python --version

      - name: Run digest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
        run: python daily_startup_to_notion.py

